config/routes.rb
Rails.application.routes.draw do
  get 'ranking/index'
  get 'flicks/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:  {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get 'my_page' => 'users/registrations#my_page'
    end
  root 'homes#index'
  resources :reviews
  resources :favorite_reviews, only: [:create, :destroy]
  resources :favorite_movies, only: [:create, :destroy]
  resources :categories
  resources :users, only: %i(index show edit)
  resources :relationships, only: [:create, :destroy]
  resources :movies do
    member do
      resources :reviews
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :name, uniqueness: true
  has_many :movie_categories, dependent: :destroy
  has_many :movies, through: :movie_categories
end

app/models/favorite_movie.rb
class FavoriteMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/favorite_review.rb
class FavoriteReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true,
            uniqueness: true,
            length: { maximum: 30 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader

  enum watched_by: [:watched_by, :Amazon_Prime, :NetFlix, :映画館, :レンタル]
  has_many :reviews, dependent: :destroy
  has_many :favorite_movies
  # has_many :favorite_movie, through: :favorite_reviews, source: :user
  has_many :movie_categories, dependent: :destroy
  has_many :categories, through: :movie_categories
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  belongs_to :movie
  belongs_to :category
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  validates :impression, presence: true, length: { maximum: 1000 }
  has_many :favorite_reviews, dependent: :destroy
  # has_many :favorite_users, through: :favorite_reviews, source: :user
  belongs_to :user, optional: true
  belongs_to :movie, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true,
            length: { maximum: 30 },
            uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  mount_uploader :icon, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :favorite_reviews, dependent: :destroy
  has_many :favo, through: :favorite_reviews, source: :review
  has_many :favorite_movies, dependent: :destroy
  has_many :favorite_movie, through: :favorite_movies, source: :movie
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :authenticate_user!
    PER = 9

  def index
    @q = Movie.ransack(params[:q])
    if params[:q].present?
      @movies = @q.result(distinct: true).page(params[:page]).per(PER)
    else
      @movies = Movie.all.page(params[:page]).per(PER)
    end
  end

  def new
    @movie = Movie.new
  end

  def show
    @movie = Movie.find(params[:id])
    @favorite = current_user.favorite_movies.find_by(movie_id: params[:id])
  end

  def edit
    redirect_to movies_path, notice: 'その行為はできません'
  end

  def create
    @movie = Movie.new(movie_params)
    if @movie.save
      redirect_to movies_path(anchor: 'some-id')
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :image, :watched_by, category_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    redirect_to movies_path, notice: 'その行為はできません'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flicks_helper.rb
module FlicksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/movies/_follow_form.html.erb
<div id="follow_form_<%= movie.id %>">
  <% unless current_user.following?(movie) %>
    <%= form_with(model: current_user.favorite_movies.build(movie_id: params[:movie_id])) do |f| %>
    <%#= form_with(model: current_user.active_relationships.build(followed_id: movie.id)) do |f| %>
      <%= f.hidden_field :movie_id %>
      <%= f.submit "like it" %>
    <% end %>
  <% else %>
    <%= form_with(model: current_user.active_relationships.find_by(followed_id: movie.id), method: :delete ) do |f| %>
      <%= f.submit "shit" %>
    <% end %>
  <% end %>
</div>

app/views/movies/edit.html.erb
<h1>Movies#edit</h1>
<p>Find me in app/views/movies/edit.html.erb</p>

app/views/movies/index.html.erb
<section class="jumbotron jumbotron-fluid text-center">
  <div class="container" id="movie">
    <% if flash[:notice]%>
    <div class="alert alert-dismissible mx-auto" role="alert">
      <%= flash[:notice] %>
    </div>
    <% end %>
    <h1 class="jumbotron-heading"><br>Flicks</h1>
    <div class="d-flex justify-content-center">
      <%= search_form_for(@q, url:movies_path(anchor:'some-id')) do |f| %>
        <div class="form-inline search_bar">
          <%= f.search_field :title_cont, class: "form-control mr-sm-2", placeholder: "作品名...", ontouchstart: ""  %>
          <%= f.submit class: "btn btn-custom search-btn" %>
        </div>
      <% end %>
    </div>
    <% unless user_signed_in? %>
      <p class="signup-btn">
        <%= link_to "登録して使う", new_user_registration_path, class:"btn btn-primary my-2" %>
      </p>
    <% end %>
  </div>
</section>
<div class="container">
  <div class="movie-top" id="some-id"><p></p></div>
  <div class="row">
    <% @movies.each_with_index do |movie, i| %>
      <% if i%3==0 %>
        <div class="col-md-3">
      <% elsif i%2==0 %>
        <div class="col-md-4">
      <% else %>
        <div class="col-md-5">
      <% end %>
        <div class="card mb-4 shadow-sm">
          <%= link_to image_tag(movie.image.url, class: "card-img-top"), movie_path(movie) %>
          <div class="card-body">
            <p class="card-text text-center"><%= movie.title %></p>
            <div class="d-flex justify-content-between align-items-center">
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div><%= paginate @movies, window: 2 %></div>
</div>

app/views/movies/new.html.erb
<div class="movie-show pt-5">
  <div class="container">
  <div class="card w-50 mx-auto">
    <div class="card-body mt-8 shadow-sm">
      <h4 class="card-title mt-3 pb-3 text-center">Movie Registration</h4>
        <%= form_with(model: @movie, local:true) do |f| %>
        <%= render 'layouts/error_message', model: f.object %>
        <div class="form-group input-group mx-auto">
          <div class="input-group-prepend">
            <span class="input-group-text"><%= fa_icon("video-camera") %></span>
          </div>
          <%= f.text_field :title, autofocus: true, autocomplete: "title", placeholder:"title" %>
        </div>
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><%= fa_icon("film") %></span>
          </div>
          <%= f.label :image %>
          <%= f.file_field :image, autofocus: true, autocomplete: "image", placeholder:"email" %>
        </div>
        <div class="form-group input-group">
          <div class="input-group-prepend">
            <span class="input-group-text"><%= fa_icon("eye") %></span>
          </div>
          <%= f.select :watched_by, Movie.watched_bies.keys.to_a, autofocus: true, autocomplete: "watched_by", placeholder:"ニックネーム" %>
        </div>
        <div class="form-group input-group mx-auto">
          <div class="form-group">
            <span class="input-group-text"><%= fa_icon("tags") %></span>
          </div>
            <% Category.all.each do |cat| %>
            <%= f.check_box :category_ids, { multiple: true, checked: cat[:checked], disabled: cat[:disabled], include_hidden: false }, cat[:id] %>
            <label><%= cat.name %></label>
            <% end %>
        </div>
          <div class="actions text-center">
            <%= f.submit "Registration", class: "btn btn-custom"%>
            <%= link_to "Back", movies_path, class: 'btn btn-custom'%></br>
          </div>
        <% end %>
      </div>
    </div>
  </div>
  </div>
</div>

app/views/movies/show.html.erb
<div class="movie-show pb-3">
  <div class="text-center">
    <% if flash[:notice] %>
      <div class="alert mx-auto" role="alert">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= image_tag @movie.image.url, :size =>'320x320' %>
  </div>
  <div class="card mx-auto text-center mb-3" style="width: 18rem;">
    <div class="card-body text-center">
      <h5 class="card-title">映画情報</h5>
        <h4 class="card-subtitle mb-2 text-muted">
        <%= @movie.title %>
          </h4>
      <p><% @movie.categories.each do |cat| %>
          <%= cat.name %>
          <% end %>
      </p>
      <p class="card-text"></p>
      <p class="button">
        <%= link_to "post-review", new_review_path(@movie, @movie.id), class: "btn btn-custom btn-lg"%></br>
      </p>
      <p class="button">
        <%= link_to "reviews", reviews_path(@movie, @movie.id), class: "btn btn-custom btn-lg"%></br>
      </p>
      <p class="button">
        <%= link_to "movies", movies_path, class: "btn btn-custom btn-lg"%></br>
      </p>
      <p>
      <% if @favorite.present? %>
        <%= link_to  favorite_movie_path(id: @movie.id), method: :delete do %>
          <i class="fa fa-star fa-1x btn btn-custom" aria-hidden="true">Bad</i>
        <% end %>
      <% else %>
        <%= link_to  favorite_movies_path(movie_id: @movie.id), method: :post do %>
          <i class="fa fa-star-o fa-1x btn btn-custom" aria-hidden="true">Good!</i>
        <% end %>
      <% end %>
    </div>
  </div>
</div>