config/routes.rb
Rails.application.routes.draw do
  get 'ranking/index'
  get 'flicks/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:  {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get 'my_page' => 'users/registrations#my_page'
    end
  root 'homes#index'
  resources :reviews
  resources :favorite_reviews, only: [:create, :destroy]
  resources :favorite_movies, only: [:create, :destroy]
  resources :categories
  resources :users, only: %i(index show edit)
  resources :relationships, only: [:create, :destroy]
  resources :movies do
    member do
      resources :reviews
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :name, uniqueness: true
  has_many :movie_categories, dependent: :destroy
  has_many :movies, through: :movie_categories
end

app/models/favorite_movie.rb
class FavoriteMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/favorite_review.rb
class FavoriteReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true,
            uniqueness: true,
            length: { maximum: 30 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader

  enum watched_by: [:watched_by, :Amazon_Prime, :NetFlix, :映画館, :レンタル]
  has_many :reviews, dependent: :destroy
  has_many :favorite_movies
  # has_many :favorite_movie, through: :favorite_reviews, source: :user
  has_many :movie_categories, dependent: :destroy
  has_many :categories, through: :movie_categories
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  belongs_to :movie
  belongs_to :category
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  validates :impression, presence: true, length: { maximum: 1000 }
  has_many :favorite_reviews, dependent: :destroy
  # has_many :favorite_users, through: :favorite_reviews, source: :user
  belongs_to :user, optional: true
  belongs_to :movie, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true,
            length: { maximum: 30 },
            uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  mount_uploader :icon, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :favorite_reviews, dependent: :destroy
  has_many :favo, through: :favorite_reviews, source: :review
  has_many :favorite_movies, dependent: :destroy
  has_many :favorite_movie, through: :favorite_movies, source: :movie
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def index
    @review = Review.all
  end

  def new
    @review = Review.new
    @movie = Movie.find(params[:format])
    @review.movie_id = @movie.id
  end

  def show
    @favorite = current_user.favorite_reviews.find_by(review_id: params[:id])
    # @favorite = current_user.favo.ids
  end

  def edit
  end

  def create
    @movie = Movie.find(params[:movie_id])
    @review = current_user.reviews.build(review_params)
    @review.movie_id = @movie.id
    if @review.save
      redirect_to review_path(@review)
    else
      render 'new'
    end
  end

  def update
  end

  def destroy
  end

  private

  def review_params
    params.require(:review).permit(:impression)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    redirect_to movies_path, notice: 'その行為はできません'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flicks_helper.rb
module FlicksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/reviews/_fllow_movie.html.erb
<% unless @review.user_id == current_user.id %>
  <% if @favorite.present? %>
    <%= link_to favorite_review_path(id: @review.id), method: :delete do %>
      <i class="fa fa-thumbs-up mx-auto" aria-hidden="true">bad</i>
    <% end %>
  <% else %>
    <%= link_to favorite_reviews_path(review_id: @review.id), method: :post do %>
      <i class="fa fa-thumbs-o-up mx-auto" aria-hidden="true">good</i>
    <% end %>
  <% end %>
<% end %>

app/views/reviews/edit.html.erb
<h1>Reviews#edit</h1>
<p>Find me in app/views/reviews/edit.html.erb</p>

app/views/reviews/index.html.erb
<div class="review">
  <div class="container pt-3" %>
    <h2>Reviews</h2>
    <% @movie = Movie.find(params[:format]) %>
    <div class="video-info justify-content-center d-flex">
    <%= image_tag @movie.image.url, :size =>'320x320' %>
    </div>
    <div class="review-button justify-content-center d-flex"><%= link_to 'post-review', new_review_path(@movie, @movie.id), class:"btn btn-custom" %>
    </div></br>
    <h2><strong>Title&nbsp;&nbsp;</strong><%= @movie.title %></h2>
  <% @movie.reviews.each do |review| %>
    <div class="reviews">
      <div class="row blockquote review-item w-75 mx-auto">
        <div class="col-md-3 text-center">
          <%= link_to review_path(review) do %>
            <%= image_tag review.user.icon.url, :size =>'80x80' %><br>
            <%= review.user.name %>
          <% end %>
          <div class="caption">
          </div>
        </div>
        <div class="col-md-9">
          <%= review.impression %><br>
          <%= @movie.watched_by + "#{'で見られるよ!'}"%><br>
          <small class="review-date"><%= Date.parse(review.created_at.to_s).strftime("%Y年%m月%d日") %></small><br>
          <% unless review.user_id == current_user.id %>
            <% @favorite = current_user.favorite_reviews.find_by(review_id: review.id) %>
            <% if @favorite.present? %>
              <%= link_to favorite_review_path(id: review.id), method: :delete do %>
                <i class="fa fa-thumbs-up mx-auto" aria-hidden="true">bad</i>
              <% end %>
            <% else %>
              <%= link_to favorite_reviews_path(review_id: review.id), method: :post do %>
                <i class="fa fa-thumbs-o-up mx-auto" aria-hidden="true">good</i>
              <% end %>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
    <% end %>
    <div class="actions text-center pb-3">
      <%= link_to "movies", movies_path, class: 'btn btn-custom'%>
      <%= link_to "post-review", new_review_path(@movie, @movie.id), class: 'btn btn-custom'%>
    </div>
  </div>
</div>
</div>

app/views/reviews/new.html.erb
<div class="review">
  <div class="container">
  <%= form_with(model:@review,local: true) do |form| %>
    <%= render 'layouts/error_message', model: form.object %>
      <div class="text-center">
    <%= image_tag @movie.image.url, :size =>'320x320' %>
      </div>
    <div class="card w-50 mx-auto mb-3">
     <div class="card-body">
       <h3 class="card-title mb-4 text-center">Post-review</h3>
          <div class="field text-center">
            <%= form.text_area :impression, :size => '50x10' %>
            <%= hidden_field_tag :movie_id, @movie.id %>
          </div><br>
          <div class="actions text-center">
            <%= form.submit('POST',class: 'btn btn-custom') %>
            <%= link_to "MOVIES", movies_path, class: 'btn btn-custom' %>
          </div>
        <% end %>
     </div>
    </div>
  </div>
</div>

app/views/reviews/show.html.erb
<% @review = Review.find(params[:id]) %>
<% mov = @review.movie %>
<% @movie = Movie.find(mov.id) %>
<div class="review">
  <div class="container pt-3">
    <h2>Review</h2>
    <div class="video-info justify-content-center d-flex">
      <%= image_tag @movie.image.url, :size =>'320x320' %>
    </div><br>
    <h2><strong>Title&nbsp;&nbsp;</strong><%= @movie.title %></h2>
    <div class="row blockquote review-item w-75 mx-auto">
      <div class="col-md-3 text-center">
        <%= link_to user_path(@review.user) do %>
          <%= image_tag @review.user.icon.url, :size =>'80x80' %><br>
          <%= @review.user.name %>
        <% end %>
      </div>
      <div class="col-md-9">
        <%= @review.impression %><br>
        <%= @movie.watched_by + "でみれます！" %>
        <div class="text-center">
          <%= render 'reviews/fllow_movie' %>
        </div>
      </div>
    </div>
    <div class="actions text-center">
      <%= link_to "movies", movies_path, class: 'btn btn-custom mb-3' %><br>
      <%= link_to "reviews", reviews_path(@movie, @movie.id), class: 'btn btn-custom mb-3' %><br>
      <%= link_to "post-review", new_review_path(@movie, @movie.id), class: 'btn btn-custom mb-3' %>
    </div>
  </div>
</div>