config/routes.rb
Rails.application.routes.draw do
  get 'ranking/index'
  get 'flicks/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users, controllers:  {
    :registrations => 'users/registrations',
    :sessions => 'users/sessions'
  }
  devise_scope :user do
    get 'my_page' => 'users/registrations#my_page'
    end
  root 'homes#index'
  resources :reviews
  resources :favorite_reviews, only: [:create, :destroy]
  resources :favorite_movies, only: [:create, :destroy]
  resources :categories
  resources :users, only: %i(index show edit)
  resources :relationships, only: [:create, :destroy]
  resources :movies do
    member do
      resources :reviews
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    if user && user.admin_flg?
      can :access, :rails_admin
      can :manage, :all
    end
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates :name, presence: true, length: { maximum: 15 }
  validates :name, uniqueness: true
  has_many :movie_categories, dependent: :destroy
  has_many :movies, through: :movie_categories
end

app/models/favorite_movie.rb
class FavoriteMovie < ApplicationRecord
  belongs_to :user
  belongs_to :movie
end

app/models/favorite_review.rb
class FavoriteReview < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, presence: true,
            uniqueness: true,
            length: { maximum: 30 }
  validates :image, presence: true
  mount_uploader :image, ImageUploader

  enum watched_by: [:watched_by, :Amazon_Prime, :NetFlix, :映画館, :レンタル]
  has_many :reviews, dependent: :destroy
  has_many :favorite_movies
  # has_many :favorite_movie, through: :favorite_reviews, source: :user
  has_many :movie_categories, dependent: :destroy
  has_many :categories, through: :movie_categories
end

app/models/movie_category.rb
class MovieCategory < ApplicationRecord
  belongs_to :movie
  belongs_to :category
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :followed, class_name: "User"
  belongs_to :follower, class_name: "User"
end

app/models/review.rb
class Review < ApplicationRecord
  validates :impression, presence: true, length: { maximum: 1000 }
  has_many :favorite_reviews, dependent: :destroy
  # has_many :favorite_users, through: :favorite_reviews, source: :user
  belongs_to :user, optional: true
  belongs_to :movie, optional: true
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30 }
  validates :email, presence: true,
            length: { maximum: 30 },
            uniqueness: true,
            format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }
  mount_uploader :icon, ImageUploader
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :reviews
  has_many :favorite_reviews, dependent: :destroy
  has_many :favo, through: :favorite_reviews, source: :review
  has_many :favorite_movies, dependent: :destroy
  has_many :favorite_movie, through: :favorite_movies, source: :movie
  has_many :active_relationships, foreign_key: 'follower_id', class_name: 'Relationship', dependent: :destroy
  has_many :passive_relationships, foreign_key: 'followed_id', class_name: 'Relationship', dependent: :destroy
  has_many :following, through: :active_relationships, source: :followed
  has_many :followers, through: :passive_relationships, source: :follower

  def follow!(other_user)
    active_relationships.create!(followed_id: other_user.id)
  end

  def following?(other_user)
    active_relationships.find_by(followed_id: other_user.id)
  end

  def unfollow!(other_user)
    active_relationships.find_by(followed_id: other_user.id).destroy
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    redirect_to movies_path, notice: 'その行為はできません'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/flicks_helper.rb
module FlicksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/ranking_helper.rb
module RankingHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_error_message.html.erb
<% if model.errors.any? %>
  <div class="alert alert-warning">
    <ul>
      <%= "#{model.errors.count}件のエラーがあります。" %>
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlickFlicks</title>
    <%#= favicon_link_tag('favicon.ico') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Alegreya+Sans+SC&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/css/swiper.min.css">
  </head>
  <nav class="navbar navbar-expand-lg ">
    <a class="navbar-brand h1">
      <% if user_signed_in? %>
        <%= link_to "Flick Flicks", movies_path %></a>
      <% else %>
        <%= link_to "Flick Flicks", root_path %></a>
      <% end %>
<!--      <img src="assets/images/f_f_event_30_svg_f_event_30_0bg.svg" width="30" height="30" class="d-inline-block align-top" alt="">-->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
        </li>
        <% if user_signed_in? && current_user.admin_flg? %>
          <li class="nav-item active"><%= link_to "post-movie", new_movie_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "movies", movies_path(anchor: 'some-id'), class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "users", users_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "ranking", ranking_index_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "flicks", flicks_index_path, class: "nav-link" %></li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
           menu
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-menu"><%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link" %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-menu"><%= link_to "admin", rails_admin_path, class: "nav-link" %></a>
            <div class="dropdown-divider"></div>
            <a class="dropdown-menu"><%= link_to "category", new_category_path, class: "nav-link" %></a>
          </div>
        </li>
        <% elsif user_signed_in? %>
          <li class="nav-item active"><%= link_to "post-movie", new_movie_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "movies", movies_path(anchor: 'some-id'), class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "users", users_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "ranking", ranking_index_path, class: "nav-link" %></li>
          <li class="nav-item active"><%= link_to "flicks", flicks_index_path, class: "nav-link" %></li>
          <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            menu
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <a class="dropdown-menu"><%= link_to "logout", destroy_user_session_path, method: :delete, class: "nav-link" %></a>
          </div>
          </li>
      </ul>
        <% else %>
          <%= link_to "SignUp", new_user_registration_path, class: "nav-link" %>
          <%= link_to "LogIn", new_user_session_path, class: "nav-link" %>
        <% end %>
      </form>
    </div>
  </nav>
  <body>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Swiper/3.4.1/js/swiper.min.js"></script>
  <%= yield %>
  </body>
  <footer class="page-footer font-small special-color-dark pt-4">
    <div class="container">
      <ul class="list-unstyled list-inline text-center">
        <li class="list-inline-item">
          <a class="btn-floating btn-fb mx-1">
            <i class="fa fa-facebook" aria-hidden="true"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-tw mx-1">
            <i class="fa fa-twitter" aria-hidden="true"></i>
          </a>
        </li>
        <li class="list-inline-item">
          <a class="btn-floating btn-gplus mx-1">
            <i class="fa fa-google" aria-hidden="true"></i>
          </a>
        </li>
        <li>
      </ul>
    </div>
    <div class="footer-copyright text-center py-3">© 2019 Copyright:
      <a href="https://takashitakeyama.github.io" target="_blank"> TakeyamaTakashi.Inc</a>
    </div>
  </footer>
</html>